In [1]:
import polars as pl

In [2]:
wd = "C:/Users/Pablo/proyects/data_pipeline_garantias/data/processed/Fotos/"

In [6]:
df_parquet = pl.read_parquet(wd + "Foto_VF_202509.parquet")
df_parquet.count()

shape: (1, 57)
┌─────────┬────────┬──────────────────┬─────────┬───┬─────────────┬───────────┬─────────┬──────────┐
│ BUCKET  ┆ CAMBIO ┆ MCrédito_MM_UDIS ┆ MM_UDIS ┆ … ┆ fecha_recup ┆ Moneda_Id ┆ pago_or ┆ recup_or │
│ ---     ┆ ---    ┆ ---              ┆ ---     ┆   ┆ ---         ┆ ---       ┆ ---     ┆ ---      │
│ u32     ┆ u32    ┆ u32              ┆ u32     ┆   ┆ u32         ┆ u32       ┆ u32     ┆ u32      │
╞═════════╪════════╪══════════════════╪═════════╪═══╪═════════════╪═══════════╪═════════╪══════════╡
│ 1961063 ┆ 216910 ┆ 216910           ┆ 2650101 ┆ … ┆ 123495      ┆ 216910    ┆ 216910  ┆ 123495   │
└─────────┴────────┴──────────────────┴─────────┴───┴─────────────┴───────────┴─────────┴──────────┘

In [10]:
df_csv = pl.read_csv(wd + "Foto_VF_202508.csv")
df_csv

shape: (2_643_527, 57)
┌────────┬─────────┬─────────────────┬─────────┬───┬─────────────┬───────────┬──────────┬──────────┐
│ BUCKET ┆ CAMBIO  ┆ MCrédito_MM_UDI ┆ MM_UDIS ┆ … ┆ fecha_recup ┆ Moneda_Id ┆ pago_or  ┆ recup_or │
│ ---    ┆ ---     ┆ S               ┆ ---     ┆   ┆ ---         ┆ ---       ┆ ---      ┆ ---      │
│ i64    ┆ f64     ┆ ---             ┆ i64     ┆   ┆ str         ┆ i64       ┆ f64      ┆ f64      │
│        ┆         ┆ f64             ┆         ┆   ┆             ┆           ┆          ┆          │
╞════════╪═════════╪═════════════════╪═════════╪═══╪═════════════╪═══════════╪══════════╪══════════╡
│ null   ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ 4      ┆ 5.32394 ┆ 3.9930e6        ┆ 0       ┆ … ┆ null        ┆ 1         ┆ 0.088406 ┆ null     │
│ -1     ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ -1     ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ 1      ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ …      ┆ …       ┆ …               ┆ …       ┆ … ┆ …           ┆ …         ┆ …        ┆ …        │
│ 4      ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ -1     ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ null   ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ -1     ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
│ 5      ┆ null    ┆ null            ┆ 0       ┆ … ┆ null        ┆ null      ┆ null     ┆ null     │
└────────┴─────────┴─────────────────┴─────────┴───┴─────────────┴───────────┴──────────┴──────────┘

In [12]:
df_parquet.schema

Schema([('BUCKET', Int16),
        ('CAMBIO', Float64),
        ('MCrédito_MM_UDIS', Float64),
        ('MM_UDIS', Int32),
        ('INTER_CLAVE', String),
        ('NOMBRE', String),
        ('RFC', String),
        ('TIPO_PERSONA', String),
        ('CLAVE_CREDITO', String),
        ('FECHA_VALOR', Datetime(time_unit='us', time_zone=None)),
        ('PLAZO_DIAS', Int32),
        ('PLAZO', Int32),
        ('FVTO', Datetime(time_unit='us', time_zone=None)),
        ('FECHA_REGISTRO_GARANTIA', Datetime(time_unit='us', time_zone=None)),
        ('MGI (MDP)', Float64),
        ('Porcentaje Garantizado', Float32),
        ('BANCO', String),
        ('FECHA_PRIMER_INCUM', Datetime(time_unit='us', time_zone=None)),
        ('MONTO CREDITO (MDP)', Float64),
        ('SALDO (MDP)', Float64),
        ('TPRO_CLAVE', Int32),
        ('CLAVE_TAXO', Int32),
        ('TAXONOMIA', String),
        ('NR_R', String),
        ('FECHA_VALOR1', Datetime(time_unit='us', time_zone=None)),
        ('FECHA_REGISTRO1', Datetime(time_unit='us', time_zone=None)),
        ('NUM_GAR', Int8),
        ('CSG', String),
        ('PLAZO_BUCKET', Int32),
        ('MPAGADO (MDP)', Float64),
        ('PAGADAS', Int8),
        ('INCUMPLIDO', Int8),
        ('FECHA_PAGO', Datetime(time_unit='us', time_zone=None)),
        ('Programa_Original', Int32),
        ('Programa_Id', Int32),
        ('ESTRATO_ID', Int16),
        ('SECTOR_ID', Int16),
        ('ESTADO_ID', Int32),
        ('Tipo_Credito_Id', Int16),
        ('Porcentaje_Comision_Garantia', Float32),
        ('TASA_ID', Int16),
        ('Tasa_Interes', Float32),
        ('MGI (MDP) Original', Float64),
        ('AGRUPAMIENTO_ID', Float64),
        ('ESQUEMA', String),
        ('SUBESQUEMA', String),
        ('AGRUPAMIENTO', String),
        ('FONDOS_CONTRAGARANTIA', String),
        ('CONREC_CLAVE', Int32),
        ('Describe_Desrec', String),
        ('MONTOTOTAL (MDP)', Float64),
        ('RECUPERADOS (MDP)', Float64),
        ('RESCATADOS (MDP)', Float64),
        ('fecha_recup', Datetime(time_unit='us', time_zone=None)),
        ('Moneda_Id', Int16),
        ('pago_or', Float64),
        ('recup_or', Float64)])

In [11]:
df_csv.schema

Schema([('BUCKET', Int64),
        ('CAMBIO', Float64),
        ('MCrédito_MM_UDIS', Float64),
        ('MM_UDIS', Int64),
        ('INTER_CLAVE', Int64),
        ('NOMBRE', String),
        ('RFC', String),
        ('TIPO_PERSONA', String),
        ('CLAVE_CREDITO', String),
        ('FECHA_VALOR', String),
        ('PLAZO_DIAS', Int64),
        ('PLAZO', Int64),
        ('FVTO', String),
        ('FECHA_REGISTRO_GARANTIA', String),
        ('MGI (MDP)', Float64),
        ('Porcentaje Garantizado', Float64),
        ('BANCO', String),
        ('FECHA_PRIMER_INCUM', String),
        ('MONTO CREDITO (MDP)', Float64),
        ('SALDO (MDP)', Float64),
        ('TPRO_CLAVE', Int64),
        ('CLAVE_TAXO', Int64),
        ('TAXONOMIA', String),
        ('NR_R', String),
        ('FECHA_VALOR1', String),
        ('FECHA_REGISTRO1', String),
        ('NUM_GAR', Int64),
        ('CSG', String),
        ('PLAZO_BUCKET', Int64),
        ('MPAGADO (MDP)', Float64),
        ('PAGADAS', Int64),
        ('INCUMPLIDO', Int64),
        ('FECHA_PAGO', String),
        ('Programa_Original', Int64),
        ('Programa_Id', Int64),
        ('ESTRATO_ID', Int64),
        ('SECTOR_ID', Int64),
        ('ESTADO_ID', Int64),
        ('Tipo_Credito_Id', Int64),
        ('Porcentaje_Comision_Garantia', Float64),
        ('TASA_ID', Int64),
        ('Tasa_Interes', Float64),
        ('MGI (MDP) Original', Float64),
        ('AGRUPAMIENTO_ID', Float64),
        ('ESQUEMA', String),
        ('SUBESQUEMA', String),
        ('AGRUPAMIENTO', String),
        ('FONDOS_CONTRAGARANTIA', String),
        ('CONREC_CLAVE', Int64),
        ('Describe_Desrec', String),
        ('MONTOTOTAL (MDP)', Float64),
        ('RECUPERADOS (MDP)', Float64),
        ('RESCATADOS (MDP)', Float64),
        ('fecha_recup', String),
        ('Moneda_Id', Int64),
        ('pago_or', Float64),
        ('recup_or', Float64)])

In [11]:
print(df_parquet.estimated_size(unit='mb'))
print(df_csv.estimated_size(unit='mb'))

976.3040952682495
1521.924162864685