In [8]:
import polars as pl

In [9]:
wd = "C:/Users/Pablo/proyects/data_pipeline_garantias/data/processed/Fotos/"
df_parquet = pl.read_parquet(wd + "Foto_VF_202509.parquet")
df_parquet.count()

shape: (1, 57)
┌─────────┬────────┬──────────────────┬─────────┬───┬─────────────┬───────────┬─────────┬──────────┐
│ BUCKET  ┆ CAMBIO ┆ MCrédito_MM_UDIS ┆ MM_UDIS ┆ … ┆ fecha_recup ┆ Moneda_Id ┆ pago_or ┆ recup_or │
│ ---     ┆ ---    ┆ ---              ┆ ---     ┆   ┆ ---         ┆ ---       ┆ ---     ┆ ---      │
│ u32     ┆ u32    ┆ u32              ┆ u32     ┆   ┆ u32         ┆ u32       ┆ u32     ┆ u32      │
╞═════════╪════════╪══════════════════╪═════════╪═══╪═════════════╪═══════════╪═════════╪══════════╡
│ 1961063 ┆ 216910 ┆ 216910           ┆ 2650101 ┆ … ┆ 123495      ┆ 216910    ┆ 216910  ┆ 123495   │
└─────────┴────────┴──────────────────┴─────────┴───┴─────────────┴───────────┴─────────┴──────────┘

In [10]:
df_parquet.head()

shape: (5, 57)
┌────────┬────────┬──────────────────┬─────────┬───┬──────────────┬───────────┬─────────┬──────────┐
│ BUCKET ┆ CAMBIO ┆ MCrédito_MM_UDIS ┆ MM_UDIS ┆ … ┆ fecha_recup  ┆ Moneda_Id ┆ pago_or ┆ recup_or │
│ ---    ┆ ---    ┆ ---              ┆ ---     ┆   ┆ ---          ┆ ---       ┆ ---     ┆ ---      │
│ i16    ┆ f64    ┆ f64              ┆ i32     ┆   ┆ datetime[μs] ┆ i16       ┆ f64     ┆ f64      │
╞════════╪════════╪══════════════════╪═════════╪═══╪══════════════╪═══════════╪═════════╪══════════╡
│ null   ┆ null   ┆ null             ┆ 0       ┆ … ┆ null         ┆ null      ┆ null    ┆ null     │
│ null   ┆ null   ┆ null             ┆ 0       ┆ … ┆ null         ┆ null      ┆ null    ┆ null     │
│ null   ┆ null   ┆ null             ┆ 0       ┆ … ┆ null         ┆ null      ┆ null    ┆ null     │
│ -1     ┆ null   ┆ null             ┆ 0       ┆ … ┆ null         ┆ null      ┆ null    ┆ null     │
│ 4      ┆ null   ┆ null             ┆ 1       ┆ … ┆ null         ┆ null      ┆ null    ┆ null     │
└────────┴────────┴──────────────────┴─────────┴───┴──────────────┴───────────┴─────────┴──────────┘

In [26]:
(df_parquet
 .select([
     'MGI (MDP)',
     'MONTO CREDITO (MDP)',
     'SALDO (MDP)',
     'MPAGADO (MDP)',
     'PAGADAS',
     'MGI (MDP) Original',
     'MONTOTOTAL (MDP)',
     'RECUPERADOS (MDP)',
     'RESCATADOS (MDP)'
 ])
 .sum().transpose(include_header=True)
 )

shape: (9, 2)
┌─────────────────────┬───────────────┐
│ column              ┆ column_0      │
│ ---                 ┆ ---           │
│ str                 ┆ f64           │
╞═════════════════════╪═══════════════╡
│ MGI (MDP)           ┆ 1.0171e6      │
│ MONTO CREDITO (MDP) ┆ 2.2575e6      │
│ SALDO (MDP)         ┆ 129763.087654 │
│ MPAGADO (MDP)       ┆ 62462.036326  │
│ PAGADAS             ┆ 216907.0      │
│ MGI (MDP) Original  ┆ 813180.296687 │
│ MONTOTOTAL (MDP)    ┆ 19152.663395  │
│ RECUPERADOS (MDP)   ┆ 15115.163067  │
│ RESCATADOS (MDP)    ┆ 4127.16869    │
└─────────────────────┴───────────────┘